// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJnQmePRrT55RQfFsowWnxecDmRbD-TE',
    appId: '1:531925018149:web:833328a9baffe2e2c401cc',
    messagingSenderId: '531925018149',
    projectId: 't0d0-4357e',
    authDomain: 't0d0-4357e.firebaseapp.com',
    storageBucket: 't0d0-4357e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LaFAEbZMFssp2c_ha7M_iSW-G--_wDg',
    appId: '1:531925018149:android:c27c33d56249a55cc401cc',
    messagingSenderId: '531925018149',
    projectId: 't0d0-4357e',
    storageBucket: 't0d0-4357e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiF_n5oly9h2iFFL6AdUM0PYEJ8PuvNo',
    appId: '1:531925018149:ios:36786d9b63d66042c401cc',
    messagingSenderId: '531925018149',
    projectId: 't0d0-4357e',
    storageBucket: 't0d0-4357e.appspot.com',
    iosBundleId: 'com.example.t0d0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiF_n5oly9h2iFFL6AdUM0PYEJ8PuvNo',
    appId: '1:531925018149:ios:36786d9b63d66042c401cc',
    messagingSenderId: '531925018149',
    projectId: 't0d0-4357e',
    storageBucket: 't0d0-4357e.appspot.com',
    iosBundleId: 'com.example.t0d0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJnQmePRrT55RQfFsowWnxecDmRbD-TE',
    appId: '1:531925018149:web:db95061fcb2b1887c401cc',
    messagingSenderId: '531925018149',
    projectId: 't0d0-4357e',
    authDomain: 't0d0-4357e.firebaseapp.com',
    storageBucket: 't0d0-4357e.appspot.com',
  );
}
